from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import viewsets, status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from core.models import Article

from article import serializers


class ArticleViewSet(viewsets.ModelViewSet):
    """Manage Articles in the database"""
    serializer_class = serializers.ArticleSerializer
    queryset = Article.objects.all()
    permission_classes = (IsAuthenticatedOrReadOnly,)
    authentication_classes = (TokenAuthentication,)

    def perform_create(self, serializer):
        """To return the article object"""
        serializer.save(user=self.request.user)

    def get_queryset(self):
        """Order return object"""
        return self.queryset.order_by('-id')

    def get_serializer_class(self):
        """Return appropriate serializer class"""
        if self.action == 'upload_image':
            return serializers.ArticleImageSerializer

        return self.serializer_class

    @action(methods=['POST'], detail=True, url_path='upload-image')
    def upload_image(self, request, pk=None):
        """Upload image to article"""
        article = self.get_object()
        serializer = self.get_serializer(
            article,
            data=request.data
        )

        if serializer.is_valid():
            serializer.save()
            return Response(
                serializer.data,
                status.HTTP_200_OK
            )

        # Return error generated by serializer if invalid request
        return Response(
            serializer.errors,
            status.HTTP_400_BAD_REQUEST
        )
